### ISSUE TITLE
Not getting "onEvent" callback on some devices 

### ISSUE THREAD

**Issue by ghost** [kontaktio/kontakt-android-sdk#101]
Hi, 
I am running into this issue where the bluetooth adapter is able to scan devices (I can see devices and theri RSSI in the logs) but I am not getting any `onEvent` (from `ProximityManager.ProximityListener`). I am continuously seeing `D/BluetoothAdapter: startLeScan(): null` and `D/BluetoothAdapter: stopLeScan()` logs in logcat which are not on the devices where it is working perfectly. Devices on which it is not working are `samsung s3, OS version 4.3`, `Samsung E5, OS version 5.1` and `Motorolla droid razor, OS version 4.4.2`. And the devices on which it is working are `Nexus 6, OS version 6.0`, `Note 4, OS version 5.1` and `Nexus 4, cannot verify OS version atm`. We only have these 6 devices and the kontakt setup is not working for 50% of our devices which is a bit concerning. I have followed the official step-by-step process mentioned on kontakt developers support page. Here is how I have done it.

``` java
public class MainActivity extends BaseActivity
        implements ProximityManager.ProximityListener
{
    private Context context;
    private ProximityManagerContract proximityManager;
    private ScanContext scanContext;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        context = this;
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (BluetoothUtils.isBleSupported(this))
        {
            KontaktSDK.initialize("WDJyccVSIaKWnkUYxLVQKSoaAVqtWVqS").
                    setDebugLoggingEnabled(BuildConfig.DEBUG)
                      .setLogLevelEnabled(LogLevel.VERBOSE, true);

            proximityManager = new KontaktProximityManager(this);
        }
    }

    @Override
    protected void onStart()
    {
        super.onStart();

        if (BluetoothUtils.isBleSupported(context))
        {
            proximityManager.initializeScan(
                    getScanContext(),
                    new OnServiceReadyListener()
                    {
                        @Override
                        public void onServiceReady()
                        {
                            proximityManager.attachListener(MainActivity.this);
                        }

                        @Override
                        public void onConnectionFailure()
                        {

                        }
                    });
        }
    }

    @Override
    public void onStop()
    {
        super.onStop();
        if (BluetoothUtils.isBleSupported(context))
        {
            proximityManager.detachListener(this);
            proximityManager.disconnect();
        }
    }

    private ScanContext getScanContext()
    {
        if (scanContext == null)
        {
            scanContext = new ScanContext.Builder()
                    .setScanPeriod(ScanPeriod.RANGING) // or for monitoring for 15 seconds scan and 10 seconds waiting:
//                    .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(15), TimeUnit.SECONDS.toMillis(10)))
                    .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
                    .setActivityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                    .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                    .setIBeaconScanContext(new IBeaconScanContext.Builder().build())
                    .setEddystoneScanContext(new EddystoneScanContext.Builder().build())
                    .setForceScanConfiguration(ForceScanConfiguration.MINIMAL)
                    .build();
        }
        return scanContext;
    }

@Override
    public void onScanStart()
    {
        Log.d(TAG, "scan started");
    }

    @Override
    public void onScanStop()
    {
        Log.d(TAG, "scan stopped");
    }

    @Override
    public void onEvent(BluetoothDeviceEvent bluetoothDeviceEvent)
    {
        Log.d(TAG, "onEvent");
        List<? extends RemoteBluetoothDevice> deviceList = bluetoothDeviceEvent.getDeviceList();
        long timestamp = bluetoothDeviceEvent.getTimestamp();
        DeviceProfile deviceProfile = bluetoothDeviceEvent.getDeviceProfile();
        switch (bluetoothDeviceEvent.getEventType())
        {
            case SPACE_ENTERED:
                Log.d(TAG, "namespace or region entered");
                break;
            case DEVICE_DISCOVERED:
                Log.d(TAG, "found new beacon, id : " + deviceList.get(0).getUniqueId());
                //I am doing my work here
        break;
            case DEVICES_UPDATE:
                Log.d(TAG, "updated beacons");
                break;
            case DEVICE_LOST:
                Toast.makeText(context, "un-camped from : " + deviceList.get(0).getUniqueId(), Toast.LENGTH_SHORT).show();
                Log.d(TAG, "lost device");
                break;
            case SPACE_ABANDONED:
                Log.d(TAG, "namespace or region abandoned");
                break;
        }
    }
}
```

Here is the log output when logcat is filtered via "kontakt" query.

```
03-22 11:59:22.089 24233-24233/com.dealsmash.dealsmashapp D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@41e38708 className=com.kontakt.sdk.android.ble.service.ProximityService packageName=com.dealsmash.dealsmashapp intent=null}
03-22 11:59:22.090 24233-24233/com.dealsmash.dealsmashapp D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@41e38708 className=com.kontakt.sdk.android.ble.service.ProximityService packageName=com.dealsmash.dealsmashapp intent=null}
03-22 11:59:22.091 24233-24233/com.dealsmash.dealsmashapp D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@41e38708 intent=Intent { cmp=com.dealsmash.dealsmashapp/com.kontakt.sdk.android.ble.service.ProximityService }}
03-22 11:59:22.629 24233-24233/com.dealsmash.dealsmashapp E/dalvikvm: Could not find class 'android.bluetooth.le.ScanSettings$Builder', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.createScanConfiguration
03-22 11:59:22.629 24233-24233/com.dealsmash.dealsmashapp W/dalvikvm: VFY: unable to resolve new-instance 71 (Landroid/bluetooth/le/ScanSettings$Builder;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-22 11:59:22.630 24233-24233/com.dealsmash.dealsmashapp I/dalvikvm: Could not find method android.bluetooth.BluetoothAdapter.getBluetoothLeScanner, referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.getScanner
03-22 11:59:22.633 24233-24233/com.dealsmash.dealsmashapp E/dalvikvm: Could not find class 'android.bluetooth.le.ScanCallback', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.onScanStart
03-22 11:59:22.633 24233-24233/com.dealsmash.dealsmashapp W/dalvikvm: VFY: unable to resolve check-cast 70 (Landroid/bluetooth/le/ScanCallback;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-22 11:59:22.634 24233-24233/com.dealsmash.dealsmashapp E/dalvikvm: Could not find class 'android.bluetooth.le.ScanCallback', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.onScanStop
03-22 11:59:22.634 24233-24233/com.dealsmash.dealsmashapp W/dalvikvm: VFY: unable to resolve check-cast 70 (Landroid/bluetooth/le/ScanCallback;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-22 11:59:22.635 24233-24233/com.dealsmash.dealsmashapp D/dalvikvm: DexOpt: unable to opt direct call 0x0185 at 0x25 in Lcom/kontakt/sdk/android/ble/service/ScanCompat;.createScanConfiguration
```

We are on a very crucial stage with our venture, so any help will be appreciated. Let me know if you need anything else for troubleshooting the issue.
Much Thanks.

**Comment by michaldrabik** [comment]
@KashanDanish What version of Kontakt SDK are you using. Have you added SDK via JAR file or Gradle dependency?

EDIT Also could you show your `AndroidManifest` file?

**Comment by ghost** [comment]
@michaldrabik thanks for replying. My SDK version is `2.1.1`. I included SDK via Gradle dependency.
Here is my manifest file.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.dealsmash.dealsmashapp">

    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="true" />

    <application
        android:allowBackup="true"
        android:icon="@drawable/logo_ds"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/Base.Theme"
        android:name="com.dealsmash.dealsmashapp.DealSmashApplication">

        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/app_id" />

        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_maps_key" />

        <meta-data
            android:name="kontakt.io.API_KEY"
            android:value="@string/kontakt_io_api_key" />

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

        <activity
            android:name=".ui.LoginActivity"
            android:windowSoftInputMode="adjustPan">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name=".ui.core.MainActivity">

            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable" />
        </activity>

        <activity
            android:name=".ui.core.StoreDetailActivity"
            android:label=""
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name=".ui.core.KickDetailActivity"
            android:label=""
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name=".ui.core.ProductDetailActivity"
            android:label=""
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name=".ui.ViewSamplesActivity"
            android:label="Samples"
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name=".ui.SavedCouponsActivity"
            android:label="Coupons" />

        <activity
            android:name=".ui.CouponPreviewActivity"
            android:label="Coupons"
            android:theme="@style/TransparentActivityTheme"/>

        <activity
            android:name=".ui.RewardsActivity"
            android:label="Rewards"/>

        <activity
            android:name=".ui.FilteredKicksListActivity"
            android:label="Rewards"/>

        <activity
            android:name=".ui.SettingsActivity"
            android:label="Settings"
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name=".ui.UserProfile"
            android:label="Profile"
            android:windowSoftInputMode="stateHidden"
            android:parentActivityName=".ui.core.MainActivity" />

        <activity
            android:name="com.dealsmash.dealsmashapp.ui.MapsActivity"
            android:label="Map">
        </activity>

        <activity
            android:name="com.dealsmash.dealsmashapp.ui.InterestsActivity"
            android:label="Map">
        </activity>

        <service
            android:name="com.dealsmash.dealsmashapp.recievers.GeofencingReceiver"
            android:exported="true"
            android:label="@string/app_name" />

        <service android:name=".services.PeriodicTasksService"/>

        <service android:name=".services.BeaconRangingService"/>

        <service android:name=".services.BeaconTrackingService"/>

        <service
            android:name="com.kontakt.sdk.android.ble.service.ProximityService"
            android:exported="false"/>
    </application>

</manifest>
```

**Comment by michaldrabik** [comment]
All seems fine. Got one more thing to ask - could you download nRF Master Control Panel App (https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) on the device with the problems and tell me if nRF app can see the beacons.

**Comment by ghost** [comment]
Okay, ill let you know when i get the results. Thanks

**Comment by ghost** [comment]
@michaldrabik Yes I can see the device list in the app you mentioned. Do you need some other information from this nRF app?

**Comment by michaldrabik** [comment]
@KashanDanish It's hard for me to give you immediate fix for the problem. Given the fact that, as you described, same code works well on Note with Android 5.1 but doesn't work on Samsung E5 with the same OS it seems like its more of a hardware problem with specific device than the SDK. Judging from the logs, It seems that there is no 
https://developer.android.com/reference/android/bluetooth/le/ScanSettings.html available on phone.

I'll try to dig deeper into the problem and get back to you if we find anything.

**Comment by ghost** [comment]
Okay, thanks for looking into it for us. But what is alarming for us that it is not working for three very different devices so who might know when we go production, what is awaiting for us.

**Comment by ghost** [comment]
One thing i would like to add that I am using two beacon related services (as mentioned in Manifest) `BeaconRangingService` and `BeaconTrackingService`. Ranging service scans for beacons when the app is in background and tracking service keeps records of beacon ids so we dont do any action on it again for a a specific time period. I am just mentioning these so that may be they has something to do with the situation.

**Comment by michaldrabik** [comment]
@KashanDanish Thanks. Unfortunately Android BLE support across different devices has always been very immature. It is a well know problem among the developers.

As for the services we can easily check if they are causing any problems. Try building and running new project with the simplest possible example: http://developer.kontakt.io/android-sdk/2.1.0/quickstart/#basic-usage-ranging-monitoring-beacons on the Samsung E5, for instance, and see if same problems occur.

**Comment by ghost** [comment]
@michaldrabik I installed a barebones app with basic Kontakt.IO functionality on E5. It is still not working but I am seeing a new pattern in logs. 

``` java
03-24 10:28:15.380 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@41e52678 className=com.kontakt.sdk.android.ble.service.ProximityService packageName=com.dealsmash.basicbletest intent=null}
03-24 10:28:15.382 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@41e52678 className=com.kontakt.sdk.android.ble.service.ProximityService packageName=com.dealsmash.basicbletest intent=null}
03-24 10:28:15.387 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-BIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@41e52678 intent=Intent { cmp=com.dealsmash.basicbletest/com.kontakt.sdk.android.ble.service.ProximityService }}
03-24 10:28:15.995 13030-13030/com.dealsmash.basicbletest E/dalvikvm: Could not find class 'android.bluetooth.le.ScanSettings$Builder', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.createScanConfiguration
03-24 10:28:15.995 13030-13030/com.dealsmash.basicbletest W/dalvikvm: VFY: unable to resolve new-instance 48 (Landroid/bluetooth/le/ScanSettings$Builder;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-24 10:28:16.000 13030-13030/com.dealsmash.basicbletest I/dalvikvm: Could not find method android.bluetooth.BluetoothAdapter.getBluetoothLeScanner, referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.getScanner
03-24 10:28:16.007 13030-13030/com.dealsmash.basicbletest E/dalvikvm: Could not find class 'android.bluetooth.le.ScanCallback', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.onScanStart
03-24 10:28:16.008 13030-13030/com.dealsmash.basicbletest W/dalvikvm: VFY: unable to resolve check-cast 45 (Landroid/bluetooth/le/ScanCallback;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-24 10:28:16.011 13030-13030/com.dealsmash.basicbletest E/dalvikvm: Could not find class 'android.bluetooth.le.ScanCallback', referenced from method com.kontakt.sdk.android.ble.service.ScanCompat.onScanStop
03-24 10:28:16.031 13030-13030/com.dealsmash.basicbletest W/dalvikvm: VFY: unable to resolve check-cast 45 (Landroid/bluetooth/le/ScanCallback;) in Lcom/kontakt/sdk/android/ble/service/ScanCompat;
03-24 10:28:16.033 13030-13030/com.dealsmash.basicbletest D/dalvikvm: DexOpt: unable to opt direct call 0x00f9 at 0x25 in Lcom/kontakt/sdk/android/ble/service/ScanCompat;.createScanConfiguration
03-24 10:28:16.403 13030-13068/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.manager.KontaktProximityListener.onScanStart(KontaktProximityListener.java:42)
03-24 10:28:16.403 13030-13068/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.MonitorCallback.onScanStarted(MonitorCallback.java:104)
03-24 10:28:16.405 13030-13068/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.Runners$3.run(Runners.java:107)
03-24 10:28:16.406 13030-13068/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.ScanController$Consumer.run(ScanController.java:174)
03-24 10:28:20.170 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-UNBIND_SERVICE handled : 0 / BindServiceData{token=android.os.BinderProxy@41e52678 intent=Intent { cmp=com.dealsmash.basicbletest/com.kontakt.sdk.android.ble.service.ProximityService }}
03-24 10:28:20.170 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-Destroying service: com.kontakt.sdk.android.ble.service.ProximityService@41e60a10
03-24 10:28:22.045 13030-13030/com.dealsmash.basicbletest D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@41ed5820 className=com.kontakt.sdk.android.ble.service.ProximityService packageName=com.dealsmash.basicbletest intent=null}
```

These lines are repeating again and again now. (This is also the logcat filtered with "kontakt" query).

**Comment by ghost** [comment]
This is the full `System.err` exception stack from above logcat without the "Kontakt" query.

```
03-24 10:49:16.920 26932-26973/com.dealsmash.basicbletest W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
03-24 10:49:16.921 26932-26973/com.dealsmash.basicbletest W/System.err:     at android.os.Handler.<init>(Handler.java:208)
03-24 10:49:16.921 26932-26973/com.dealsmash.basicbletest W/System.err:     at android.os.Handler.<init>(Handler.java:122)
03-24 10:49:16.921 26932-26973/com.dealsmash.basicbletest W/System.err:     at android.widget.Toast$TN.<init>(Toast.java:338)
03-24 10:49:16.921 26932-26973/com.dealsmash.basicbletest W/System.err:     at android.widget.Toast.<init>(Toast.java:92)
03-24 10:49:16.921 26932-26973/com.dealsmash.basicbletest W/System.err:     at android.widget.Toast.makeText(Toast.java:252)
03-24 10:49:16.922 26932-26973/com.dealsmash.basicbletest W/System.err:     at com.dealsmash.basicbletest.MainActivity.onScanStart(MainActivity.java:116)
03-24 10:49:16.922 26932-26973/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.manager.KontaktProximityListener.onScanStart(KontaktProximityListener.java:42)
03-24 10:49:16.922 26932-26973/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.MonitorCallback.onScanStarted(MonitorCallback.java:104)
03-24 10:49:16.922 26932-26973/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.Runners$3.run(Runners.java:107)
03-24 10:49:16.923 26932-26973/com.dealsmash.basicbletest W/System.err:     at com.kontakt.sdk.android.ble.service.ScanController$Consumer.run(ScanController.java:174)
```

**Comment by Svoka** [comment]
Why issue is closed? Do you fixed this?
