### ISSUE TITLE
BTLE Scan going crazy and it's ignoring ACTIVE and PASIVE Scan internal draning lots of Battery

### ISSUE THREAD

**Issue by rahulsindhu** [kontaktio/kontakt-android-sdk#123]
Hi,
Scan for my devices just goes crazy and keep scanning without a break. This is causing battery drain for my device. It seems to be random and we are using SDK version 3.1.1 and device is a Nexus 5 running Android 6.

I have observed an exception from stack
09-03 18:03:51.058 13955-29956/<PACKAGE_NAME> E/BluetoothLeScanner: application registeration exception
                                                                        java.lang.InterruptedException
                                                                            at java.lang.Object.wait(Native Method)
                                                                            at java.lang.Object.wait(Object.java:423)
                                                                            at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegisteration(BluetoothLeScanner.java:265)
                                                                            at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:156)
                                                                            at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:115)
                                                                            at com.kontakt.sdk.android.ble.service.RunnersL$3.run(RunnersL.java:100)
                                                                            at java.lang.Thread.run(Thread.java:818)

After this exception everything just keeping running till i switch Off and ON the Bluetooth adapter. Please check it out. Also not getting call to SCAN Error callback either form the SDK.

regards
Rahul

**Comment by michaldrabik** [comment]
@rahulsindhu This is actually an Android problem. Seems like bluetooth stack has some race conditions (here's an issue: https://code.google.com/p/android/issues/detail?id=173991).

I assume you have force scan enabled in your proximity manager configuration. 

The easy way to avoid this problem is to turn off force scan (Nexus 5 should not need it anyway). Other option is to switch from ForceScan.MINIMAL to a custom one with higher intervals (MINIMAL is (1000, 500) ms).

**Comment by rahulsindhu** [comment]
Thanks. I could figure that out but somehow if i use ForceScan custom configuration, Beacon Detection does not work. It's working on when i disable it though. But again it's very unpredictable. Like i see BEACON left message even when i have it very close to me. Anyways it will do more detail analysis soon.

Would like to know the side effect of ForceScan custom intervals and when it's disabled. What does it actually do? Why have you kept these interval as minimum by default?

It would be great if there could be a callback to notify the user of the stack about the mode of BTLE scan. This way we could test and adapt various Android Stack issues our self.  Like in this case i could see disabling and enabling BT Adapter could fix it :) and could be just start new Scan by cleaing Proximity Manager Stack .

Would like to have more control on how it's does for my project from Kontakt SDK.

**Comment by michaldrabik** [comment]
The only thing force scan does is stop and start bluetooth adapter periodically. It can be useful to counter another BLE related bug (thanks android). Mostyl for devices with 4.X. 

You can read about it here: https://code.google.com/p/android/issues/detail?id=65863
