### ISSUE TITLE
Kontakt Android SDK issue - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by abhirav** [kontaktio/kontakt-android-sdk#125]
Hi,
Many times when BLE scanning is running, I am getting below error in Android KITKAT version and app is crashed. 

`java.util.ConcurrentModificationException
                                                                          at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                          at com.kontakt.sdk.android.ble.discovery.AbstractBluetoothDeviceDiscoverer.evictInactiveDevices(Unknown Source)
                                                                          at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.evictInactiveDevices(Unknown Source)
                                                                          at com.kontakt.sdk.android.ble.service.MonitorCallback.evictInactiveDevices(Unknown Source)
                                                                          at com.kontakt.sdk.android.ble.service.MonitorCallback$1.run(Unknown Source)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5586)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                          at dalvik.system.NativeStart.main(Native Method)`

Could you have a look and let me the the actual problem and resolution?
I am using 3.1.1-RC2 version.

Thanks,
Abhi.

**Comment by michaldrabik** [comment]
@abhirav Hi, please update to newest version 3.1.1.
`compile 'com.kontaktio:sdk:3.1.1'`

This error should be fixed in 3.1.1. Let me know.

Regards

**Comment by abhirav** [comment]
Hi @michaldrabik ,
I tested and its working in my device. Will monitor crash analytics of production app if this issue still exists.
Thanks.
