### ISSUE TITLE
java.lang.IllegalStateException: BT Adapter is not turned ON

### ISSUE THREAD

**Issue by abhirav** [kontaktio/kontakt-android-sdk#126]
Hi,
I am getting below error in HTC (OS v6.0.1) device. Could you have a look? thanks.

`java.lang.IllegalStateException: BT Adapter is not turned ON
at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
at android.bluetooth.le.BluetoothLeScanner$1.handleMessage(BluetoothLeScanner.java:85)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:168)
at android.app.ActivityThread.main(ActivityThread.java:5885)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)`

**Comment by michaldrabik** [comment]
When does it happen exactly. Are you able to reproduce it or its occuring randomly?

**Comment by abhirav** [comment]
hi @michaldrabik, 
I am not able to reproduce it. I can see that in our crash analytics dashboard on HTC devices. 
Something related to [this](https://github.com/kontaktio/kontakt-android-sdk/issues/7) issue?

**Comment by michaldrabik** [comment]
@abhirav I can't relate to this one because I haven't been with Kontakt.io back then. Honestly I personally have not encountered this issue yet, and we are working with the SDK every day. Maybe it is something related to one HTC specific device.

**Comment by Mukesh-Singh** [comment]
Hi @michaldrabik I am getting the same crash on HTC One A9

`Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeScanner$1.handleMessage(BluetoothLeScanner.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5821)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)`

Could you please, look into this error ?

**Comment by michaldrabik** [comment]
Oh hey, It's HTC once again :) When does this happen exactly? During scan, randomly, always? It says that Bluetooth Adapter is not turned ON, is it actually not turned on? Regards.

**Comment by Mukesh-Singh** [comment]
Actually i got this log on crashlytics, so i am not very much sure that when it happen exactly. But i am sure it happening during scan. 
One more thing is that Bluetooth is ON because we start scanning when Bluetooth turn ON.

**Comment by michaldrabik** [comment]
It's really hard to say why it crashes only on HTC device. The `checkAdapterStateOn` method that throws the exception is part of Android SDK, not Kontakt.io. Perhaps you could get any more information from this user of your app about when does this happen and if he is doing anything weird with the Bluetooth.

**Comment by stan-ko** [comment]
My statistic looks like this:
http://prntscr.com/edw4am
HTC One (E8) dual sim - 51%
HTC Desire 630 dual sim - 17%
HTC ONE M8s - 8%
HTC One (E8) - 4%
HTC Desire EYE4 - %
HTC One A9 - 3%
HTC Desire 820 - 2%
HTC One_E8 - 1%
HTC Desire 626s - 1%
HTC Desrie D530 - 1%
HTC M10 - 1%
HTC One (M8 Eye) - 1%
HTC Desire626s - 1%
HTC_D820u - 1%
HTC Desire 10 lifestyle - 1%
HTC Desire 825 - 1%

My guess - any HTC with Android M will crash and its not the Kontakt.io SDK issue, its more like HTC firmware bug. The only workaround I found is to detect if device is HTC and its running on Android M - do not use any BT lib and particularly Kontakt.io SDK.
