### ISSUE TITLE
Application getting crash in  proximityManager.connect() method

### ISSUE THREAD

**Issue by Mukesh-Singh** [kontaktio/kontakt-android-sdk#130]
Application getting crash when  `proximityManager.connect()`  is called. In error log its saying that 

Here is the method from where i am calling `proximityManager.connect()`

```
private void startMonitoring() {
        int checkSelfPermission = ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION);

        if ((PackageManager.PERMISSION_GRANTED == checkSelfPermission) && Utils.getBluetoothState()) {
            proximityManager.connect(new OnServiceReadyListener() {
                @Override
                public void onServiceReady() {
                    Log.e(TAG, "startScanning");
                    proximityManager.startScanning();
                }
            });
        } else {
            Log.e(TAG, "Permission not guaranteed");
        }
    }
```

> java.lang.RuntimeException: Could not connect to ProximityService. Please check if the ProximityService is registered in AndroidManifest.xml

I check my `AndroidManifest.xml` and found that `ProximityService`  is registered.

Here is my service registration in xml

`
        <service
            android:name="com.kontakt.sdk.android.ble.service.ProximityService"
            android:exported="false" />`

The complete log is here

```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.forkspot.beacon.service.NewBackgroundService@42e7c7c with null: java.lang.RuntimeException: Could not connect to ProximityService. Please check if the ProximityService is registered in AndroidManifest.xml
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4079)
       at android.app.ActivityThread.access$2400(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: Could not connect to ProximityService. Please check if the ProximityService is registered in AndroidManifest.xml
       at com.kontakt.sdk.android.ble.manager.internal.InternalProximityManager.bindService(InternalProximityManager.java:216)
       at com.kontakt.sdk.android.ble.manager.internal.InternalProximityManager.connect(InternalProximityManager.java:99)
       at com.kontakt.sdk.android.ble.manager.ProximityManager.connect(ProximityManager.java:45)
       at com.forkspot.beacon.service.NewBackgroundService.startMonitoring(NewBackgroundService.java:177)
       at com.forkspot.beacon.service.NewBackgroundService.onStart(NewBackgroundService.java:153)
       at android.app.Service.onStartCommand(Service.java:459)
       at com.forkspot.beacon.service.NewBackgroundService.onStartCommand(NewBackgroundService.java:146)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4062)
       at android.app.ActivityThread.access$2400(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Please help me to resolve this issue.

**Comment by michaldrabik** [comment]
Could you please post your full AndroidManifest file?

**Comment by Mukesh-Singh** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.forkspot">

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.front"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera.front.autofocus"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="false" />

    <application
        android:name=".base.App"
        android:allowBackup="true"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:icon,android:theme">

        <!-- network state change receiver -->

        <receiver android:name=".receivers.NetworkStateChangeReceiver">
            <intent-filter>
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
        </receiver>
        <!-- [END network state change receiver] -->


        <!-- Google play service for gcm -->
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <!-- [START gcm_receiver] -->
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="com.forkspot" />
            </intent-filter>
        </receiver>
        <!-- [END gcm_receiver] -->


        <!-- [START gcm_listener] -->
        <service
            android:name=".services.AppGcmListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <!-- [END gcm_listener] -->
        <!-- [START instanceId_listener] -->
        <service
            android:name=".services.AppInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <!-- [END instanceId_listener] -->
        <!-- gcm token registration -->
        <service
            android:name=".services.RegistrationIntentService"
            android:exported="false" />

        <!-- [END gcm token registration] -->

        <activity
            android:name=".activities.LoginActivity"
            android:windowSoftInputMode="stateHidden|adjustResize" />
        <activity
            android:name=".activities.SignUpActivity"
            android:label="@string/title_activity_sign_up"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.AddPhotoActivity"
            android:label="@string/title_activity_add_photo"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.BummerActivity"
            android:label="@string/title_activity_bummer"
            android:theme="@style/AppTheme" />
        <activity android:name=".activities.ThanksActivity" />
        <activity
            android:name=".activities.SplashActivity"
            android:theme="@style/AppTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".activities.HomeActivity"
            android:label="@string/title_activity_enter_location"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.EnterLocationActivity"
            android:label="@string/title_activity_enter_location"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.RestaurantDetailsActivity"
            android:label="@string/title_activity_restaurant"
            android:parentActivityName=".activities.HomeActivity"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.SearchActivity"
            android:windowSoftInputMode="stateAlwaysVisible" />
        <activity
            android:name=".activities.DiscountActivity"
            android:label="@string/title_activity_discount"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.MaxImageViewActivity"
            android:label="@string/title_activity_max_image_view"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.AlbumsActivity"
            android:label="@string/title_activity_albums"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.RestaurantDiscountActivity"
            android:label="@string/title_activity_restaurant_discount"
            android:parentActivityName=".activities.HomeActivity"
            android:theme="@style/AppTheme">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".activities.HomeActivity" />
        </activity>

        <!--
            <activity
            android:name=".activities.RestaurantDiscountActivity"
            android:label="@string/title_activity_restaurant_discount"
            android:theme="@style/AppTheme" />
        -->
        <activity
            android:name=".activities.CommentsActivity"
            android:label="@string/title_activity_comments"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="stateHidden" />
        <activity
            android:name=".activities.ReportProblemActivity"
            android:label="@string/title_activity_report_problem"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.EditProfileActivity"
            android:label="@string/title_activity_edit_profile"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="stateHidden" />
        <activity
            android:name=".activities.VisitedRestaurantsActivity"
            android:label="@string/title_activity_visited_restaurants"
            android:theme="@style/AppTheme" />
        <activity android:name=".activities.BusinessOwnerActivity" />
        <activity android:name=".activities.ChangePasswordActivity" />
        <activity
            android:name=".activities.NotificationActivity"
            android:label="@string/title_activity_notification"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.PrivacyActivity"
            android:label="@string/title_activity_privacy"
            android:theme="@style/AppTheme" />
        <activity android:name=".activities.HurrayActivity" />
        <activity android:name=".activities.GhostActivity" />
        <activity android:name=".activities.LoveItActivity" />
        <activity android:name=".activities.FeedbackActivity" />
        <activity
            android:name=".activities.FeedBackLikeActivity"
            android:theme="@style/AppTheme" />
        <activity
            android:name=".activities.CategoryActivity"
            android:theme="@style/AppTheme.Transparent"
            android:windowSoftInputMode="stateHidden" />
        <activity android:name="com.facebook.FacebookActivity" />
        <activity
            android:name=".activities.ForgotPassActivity"
            android:noHistory="true" />

        <service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:enabled="true" />
        <service
            android:name=".services.AppLocationService"
            android:exported="false" />

        <!-- beacon -->
        <service
            android:name="com.kontakt.sdk.android.ble.service.ProximityService"
            android:exported="false" />
        <service
            android:name=".beacon.service.NewBackgroundService"
            android:enabled="true" />

        <receiver
            android:name=".beacon.receiver.NewRegionMonitorReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.forkspot.beacon.service.NewBackgroundService.BROADCAST" />
            </intent-filter>
        </receiver>
        <receiver android:name=".beacon.receiver.BluetoothStateReceiver">
            <intent-filter>
                <action android:name="android.bluetooth.adapter.action.STATE_CHANGED" />
            </intent-filter>
        </receiver>

        <service
            android:name=".beacon.service.BeaconCheckOutService"
            android:exported="true"
            android:permission="com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE">
            <intent-filter>
                <action android:name="com.google.android.gms.gcm.ACTION_TASK_READY" />
            </intent-filter>
        </service>
        <service
            android:name=".beacon.service.BeaconCheckInService"
            android:exported="true"
            android:permission="com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE">
            <intent-filter>
                <action android:name="com.google.android.gms.gcm.ACTION_TASK_READY" />
            </intent-filter>
        </service>

        <meta-data
            android:name="kontakt.io.API_KEY"
            android:value="@string/kontakt_io_api_key" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_appid" />
        <!--
             The API key for Google Maps-based APIs is defined as a string resource.
             (See the file "res/values/google_maps_api.xml").
             Note that the API key is linked to the encryption key used to sign the APK.
             You need a different API key for each encryption key, including the release key that is used to
             sign the APK for publishing.
             You can define the keys for the debug and release targets in src/debug/ and src/release/.
        -->
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_maps_key" />
        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="4a3a7a6636f7122c5c7ade4f518bc41da6c78438" />

        <activity android:name=".activities.GuestUploadActivity" />
        <activity android:name=".activities.DiscountCouponReviewActivity" />
        <activity
            android:name=".activities.WriteReviewActivity"
            android:windowSoftInputMode="stateAlwaysHidden" />
        <activity android:name=".activities.ReviewWriteThankYouActivity" />

        <provider
            android:name="com.facebook.FacebookContentProvider"
            android:authorities="com.facebook.app.FacebookContentProvider131276967296387"
            android:exported="true" />

        <receiver
            android:name=".receivers.BootReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name=".beacon.geofance.RegionMonitoringService"
            android:enabled="true"
            android:exported="false" />
        <service android:name=".beacon.geofance.GeofenceTransitionsIntentService" />

        <receiver
            android:name=".beacon.geofance.NewRestaurantGeoFenceListReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.forkspot.REGION_RESTAURANTS_BROADCAST" />
            </intent-filter>
        </receiver>
        <receiver
            android:name=".beacon.geofance.receiver.GeoFenceMonitorReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.forkspot.beacon.geofance.receiver.ACTION" />
            </intent-filter>
        </receiver>
        <receiver
            android:name=".receivers.AlarmReceiver"
            android:exported="false" />

        <service
            android:name=".services.AlarmNotificationIntentService"
            android:exported="false" />

        <receiver
            android:name=".receivers.LocationProviderStatusChangeReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.location.PROVIDERS_CHANGED" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>

        <activity android:name=".activities.FullScreenViewDiscountActivity" />
        <activity android:name=".activities.TutorialActivity" />
        <activity android:name=".activities.ThanksFeedbackActivity" />
        <activity android:name="com.mixpanel.android.surveys.SurveyActivity" />

    </application>

</manifest>
```

**Comment by michaldrabik** [comment]
@Mukesh-Singh That's really really odd. Does this happen on any particular device? Are you able to test on different phones?

**Comment by michaldrabik** [comment]
@Mukesh-Singh Also I have another question. Are you using ProGuard?

**Comment by Mukesh-Singh** [comment]
Yes, i am able to test on different phones, but this crash is happening on some devices.

Yes  i am using ProGaurd.

**Comment by michaldrabik** [comment]
I suppose you only use Proguard in your RELEASE builds. 
Does the app crash on DEBUG builds as well?

Try adding necessary rules to you `proguard-rules` file. Check out **Step 4: Proguard Configuration** in our [Quickstart](http://developer.kontakt.io/android-sdk/3.1.1/quickstart/)

**Comment by Mukesh-Singh** [comment]
You are right. its happening only with RELEASE builds, DEBUG build is working properly.

**Comment by Mukesh-Singh** [comment]
Ok, I will check this section **Step 4: Proguard Configuration**

**Comment by Mukesh-Singh** [comment]
Hi @michaldrabik I have followed the proguard rules as mentioned  here [Proguard Configuration](https://developer.kontakt.io/android-sdk/3.2.0/quickstart/#basic-usage), but still above crash is happening in release build. Please provide me any solution.
proguard-rules.pro

`# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /home/rahil/Rahil/Android/adt-bundle-linux-x86_64-20140321/sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontpreverify
-dontskipnonpubliclibraryclassmembers
-dontwarn android.webkit.**
-keepattributes *Annotation*


-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgent
-keep public class * extends android.preference.Preference
-keep public class * extends android.support.v4.app.Fragment
-keep public class * extends android.support.v4.app.DialogFragment
-keep public class * extends android.app.Fragment
-keepclasseswithmembernames class * {
 native <methods>;
}

-keep public class * extends android.view.View {
 public <init>(android.content.Context);
 public <init>(android.content.Context, android.util.AttributeSet);
 public <init>(android.content.Context, android.util.AttributeSet, int);
 public void set*(...);
}


-keepclasseswithmembers class * {
 public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
 public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class * extends android.app.Activity {
 public void *(android.view.View);
}

# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
 public static **[] values();
 public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
 public static final android.os.Parcelable$Creator *;
}

-keepclassmembers class **.R$* {
 public static <fields>;
}

-dontwarn okio.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}

-keep class com.kontakt.sdk.** { *; }
-keep interface com.kontakt.sdk.** { *; }

`
For manifest you can see above.

**Comment by michaldrabik** [comment]
@Mukesh-Singh I don't think it is a Proguard Issue. I've tested it on a sample project, tried different scenarios and everything is working fine.

Could you show me the places in your code where you call `ProximityManager`'s `connect()` method?

**Comment by Mukesh-Singh** [comment]
This is written in service which started as "START_STICKY" so that it can be run in background 
and the startMonitoring() is called from the service's `onStartCommand()` method

`public class NewBackgroundService extends Service{
 private ProximityManager proximityManager;


 @Override
    public void onCreate() {
        super.onCreate();
        proximityManager = new ProximityManager(this);
        configureProximityManager();
        //proximityManager.setScanStatusListener(this);
        proximityManager.setIBeaconListener(createIBeaconListener());
        proximityManager.setSpaceListener(createSpaceListener());
        //proximityManager.setKontaktSecureProfileListener(createProProfileListener());
    }

	private void configureProximityManager() {
        proximityManager.configuration()
                .scanMode(ScanMode.BALANCED)
                .activityCheckConfiguration(ActivityCheckConfiguration.MINIMAL)
                .forceScanConfiguration(ForceScanConfiguration.MINIMAL)
                //.deviceUpdateCallbackInterval(2000)
                .rssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
                .monitoringEnabled(true)
                .monitoringSyncInterval(3);

        addReasonForMonitoring();

        //GcmNetworkManager.getInstance(this).cancelTask();
    }


@Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        super.onStartCommand(intent, flags, startId);
	startMonitoring();
        return START_STICKY;
    }

  private void startMonitoring() {
        int checkSelfPermission = ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION);

        if ((PackageManager.PERMISSION_GRANTED == checkSelfPermission) && Utils.getBluetoothState()) {
            proximityManager.connect(new OnServiceReadyListener() {
                @Override
                public void onServiceReady() {
                    Log.e(TAG, "startScanning");
                    proximityManager.startScanning();
                }
            });
        } else {
            Log.e(TAG, "Permission not guaranteed or bluetooth is off");
        }
    }
 

}`

**Comment by michaldrabik** [comment]
@Mukesh-Singh I must say that for this moment I do not know why would your app crash there. Everything seems to be coded fine. I think we should try to run simpler example to see what the problem is.

If you can, please go to and download: https://github.com/kontaktio/kontakt-beacon-admin-sample-app/tree/new_sample_app

Open this project, run it on the device that crashes your app and see if you can run "Background Scanning" sample.

**Comment by pbertsch** [comment]
@michaldrabik  @Mukesh-Singh , any news on the issue. I have the same issue here.

**Comment by wlodzix** [comment]
I suggest adding 

service android:name="com.kontakt.sdk.android.ble.service.ProximityService"

into your AndroidManifest.xml 

it helped in my case
