### ISSUE TITLE
ClassNotFoundException: com.kontakt.sdk.android.ble.filter.ibeacon.IBeaconFilter

### ISSUE THREAD

**Issue by stan-ko** [kontaktio/kontakt-android-sdk#141]
the full stacktrace from Crashlytics is:

> Fatal Exception: java.lang.NoClassDefFoundErrorFailed resolution of: Lcom/kontakt/sdk/android/ble/filter/ibeacon/IBeaconFilter; Raw Text
> "Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kontakt/sdk/android/ble/filter/ibeacon/IBeaconFilter; at ua.ndaapp.beacon.BeaconScanService.startServiceToScan(BeaconScanService.java:166) at ua.ndaapp.app.App.onCreate(App.java:308) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5485) at android.app.ActivityThread.-wrap2(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:153) at android.app.ActivityThread.main(ActivityThread.java:6205) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) Caused by java.lang.ClassNotFoundException: com.kontakt.sdk.android.ble.filter.ibeacon.IBeaconFilter at java.lang.VMClassLoader.findLoadedClass(VMClassLoader.java) at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742) at java.lang.ClassLoader.loadClass(ClassLoader.java:362) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at ua.ndaapp.beacon.BeaconScanService.startServiceToScan(BeaconScanService.java:166) at ua.ndaapp.app.App.onCreate(App.java:308) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5485) at android.app.ActivityThread.-wrap2(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:153) at android.app.ActivityThread.main(ActivityThread.java:6205) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/util/Predicate; at ua.ndaapp.beacon.BeaconScanService.startServiceToScan(BeaconScanService.java:166) at ua.ndaapp.app.App.onCreate(App.java:308) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5485) at android.app.ActivityThread.-wrap2(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:153) at android.app.ActivityThread.main(ActivityThread.java:6205) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) Caused by java.lang.ClassNotFoundException: Didn't find class ""com.android.internal.util.Predicate"" on path: DexPathList[[zip file ""/data/app/ua.ndaapp-1/base.apk""],nativeLibraryDirectories=[/data/app/ua.ndaapp-1/lib/arm64, /system/fake-libs64, /data/app/ua.ndaapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:380) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at ua.ndaapp.beacon.BeaconScanService.startServiceToScan(BeaconScanService.java:166) at ua.ndaapp.app.App.onCreate(App.java:308) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5485) at android.app.ActivityThread.-wrap2(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1571) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:153) at android.app.ActivityThread.main(ActivityThread.java:6205) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)"

for now we only see it on one single device and it is Lenovo Lenovo K3 Note on Android 7.

**Comment by michaldrabik** [comment]
@stan-ko Just to be clear this happened only once for one of the users of your app and it does not occur on your test devices?

**Comment by stan-ko** [comment]
Not only once but seems like for only one device. It does not occur on our test devices.

**Comment by michaldrabik** [comment]
@stan-ko This kind of things are really tough to resolve (if it happens only on a single device).

> java.lang.ClassNotFoundException: Didn't find class **""**com.android.internal.util.Predicate**""** on path: DexPathList[[zip file ""/data/app/ua.ndaapp-1/base.apk""],nativeLibraryDirectories=[/data/app/ua.ndaapp-1/lib/arm64, /system/fake-libs64, /data/app/ua.ndaapp-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

This makes me think like that the problem is not really on our SDK's side. Are you using MultiDex by any chance?

**Comment by sbobowiec** [comment]
Closing this issue due to inactivity.
