### ISSUE TITLE
Crash when using KontaktSDK.initialize(Context) but don't provide API key

### ISSUE THREAD

**Issue by kevinvanmierlo** [kontaktio/kontakt-android-sdk#150]
If I'm using `KontaktSDK.initialize(Context);` but don't provide an API key in the AndroidManifest.xml the app crashes. I think because there are no meta-data keys in AndroidManifest.xml the metaData in `appInfo.metaData.getString("kontakt.io.API_KEY");` is null. So if there is a try-catch around it or a check for null this would be solved. I know I don't have to use `KontaktSDK.initialize(Context);`, but I accidentally put it in there and the crash logs just give a `NullPointerException`. Here is the Stacktrace:

```
java.lang.RuntimeException: Unable to create application com.company.test.MyApplication: java.lang.NullPointerException
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5017)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NullPointerException
    at com.kontakt.sdk.android.common.KontaktSDK.initialize(KontaktSDK.java:67)
    at com.company.test.MyApplication.onCreate(MyApplication.java:15)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
    at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:136) 
    at android.app.ActivityThread.main(ActivityThread.java:5017) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
    at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by michaldrabik** [comment]
@kevinvanmierlo Thanks for posting. The only purpose of initialization with Context is to get the ApiKey from the Manifest's meta-data. I think it makes sense to fail-fast and crash if the meta data is not there.

We will add another precondition and provide clear message what is wrong instead of just NPE.

**Comment by kevinvanmierlo** [comment]
@michaldrabik Yeah I saw that later, stupid mistake of me haha. But in case someone else makes this mistake a clear message would indeed be nice.
