### ISSUE TITLE
NoClassDefFoundError com.kontakt.sdk.android.ble.service.MonitorCallback only in Android version 4 

### ISSUE THREAD

**Issue by Susiane** [kontaktio/kontakt-android-sdk#179]
atal Exception: java.lang.NoClassDefFoundError: com.kontakt.sdk.android.ble.service.MonitorCallback
       at com.kontakt.sdk.android.ble.service.ScanCompatJB.createScanConfiguration(ScanCompatJB.java:18)
       at com.kontakt.sdk.android.ble.service.ProximityService.onStartScan(ProximityService.java:117)
       at com.kontakt.sdk.android.ble.service.ProximityService$MessagingHandler.handleMessage(ProximityService.java:207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Gloix** [comment]
I'm having the same issue on devices running Android 4.1.2 and 4.2.2. Is there a workaround for this?
These Android versions don't support Bluetooth BLE so they shouldn't be affected by the Kontakt SDK.

EDIT: There is a workaround. It involves disabling the Kontakt service by adding:
res/values/booleans/booleans.xml

    <?xml version="1.0" encoding="utf-8"?>
    <resources>
        <bool name="isGreaterThanOrEqualTo18">false</bool>
    </resources>

res/values-v18/booleans/booleans.xml

    <?xml version="1.0" encoding="utf-8"?>
    <resources>
        <bool name="isGreaterThanOrEqualTo18">true</bool>
    </resources>

AndroidManifest.xml:

    <manifest ...>
        <application ...>
            <service
                android:name="com.kontakt.sdk.android.ble.service.ProximityService"
                android:enabled="@bool/isGreaterThanOrEqualTo18"
                android:exported="false"/>
        </application>
    </manifest ...>

**Comment by robertbielas** [comment]
The definition of ScanCompatJB looks like this:

@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
final class ScanCompatJB extends ScanCompat { }

Since all of the beacon devices provided by KontaktIO operate using only BLE technology (introduced in JELLY_BEAN_MR2), systems lower than that will crash the apps hosting Android sdk on the attempt of starting ble scan.

As a personal note, the suggestion provided by @Gloix seems as a very reasonable workaround
