### ISSUE TITLE
java.util.ConcurrentModificationException at concatenateMacs()

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#206]
From Crashlytics:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.concatenateMacs(AbstractDeviceDiscoverer.java:20)
       at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.onDevicesUpdatedEvent(AbstractDeviceDiscoverer.java:76)
       at com.kontakt.sdk.android.ble.discovery.ibeacon.IBeaconDiscoverer.onShuffleResolved(IBeaconDiscoverer.java:68)
       at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.onResolved(AbstractDeviceDiscoverer.java:20)
       at com.kontakt.sdk.android.ble.discovery.ShuffledDevicesResolver.resolve(ShuffledDevicesResolver.java:50)
       at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.resolveShuffled(AbstractDeviceDiscoverer.java:22)
       at com.kontakt.sdk.android.ble.discovery.ibeacon.IBeaconDiscoverer.performDiscovery(IBeaconDiscoverer.java:140)
       at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.performDiscovery(DefaultBluetoothDeviceDiscoverer.java:18)
       at com.kontakt.sdk.android.ble.service.MonitorCallback$2.run(MonitorCallback.java:10)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by pubiqq** [comment]
@robertbielas, ping.

P. S. Sorry to bother you

**Comment by robertbielas** [comment]
@pubiqq Don't be. 

Hm, looks like a quick fix, just remove the log, it is not necessary in this place anyway. It will be in the next sdk version.

As always, thank you for vigilance.

**Comment by pubiqq** [comment]
@robertbielas, I see problematic code was removed in 5.0.11, so I suppose we can close the issue.
Thanks to your team.
