### ISSUE TITLE
java.util.ConcurrentModificationException at evictInactiveDevices()

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#210]
From Crashlytics:

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.kontakt.sdk.android.ble.discovery.AbstractDeviceDiscoverer.evictInactiveDevices(AbstractDeviceDiscoverer.java:52)
       at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.evictInactiveDevices(DefaultBluetoothDeviceDiscoverer.java:19)
       at com.kontakt.sdk.android.ble.service.MonitorCallback.evictInactiveDevices(MonitorCallback.java:2)
       at com.kontakt.sdk.android.ble.service.MonitorCallback$5.run(MonitorCallback.java:6)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by robertbielas** [comment]
@pubiqq it will be fixed in the next release, as always thanks for vigilance.

**Comment by robertbielas** [comment]
@pubiqq checkout sdk 5.0.18
