### ISSUE TITLE
Parser.extractFrameData throws an IllegalArgumentException when parsing the results of a scan

### ISSUE THREAD

**Issue by gmetal** [kontaktio/kontakt-android-sdk#212]
Hello, we are using the Kontakt SDK to scan for beacons, and sporadically, we've been receiving crash reports with the following stack trace:

```
Fatal Exception: java.lang.IllegalArgumentException: 9 > -107
       at java.util.Arrays.copyOfRange(Arrays.java:3444)
       at com.kontakt.sdk.android.ble.discovery.Parser.extractFrameData(Parser.java:61)
       at com.kontakt.sdk.android.ble.discovery.eddystone.EddystoneParser.parseFrame(EddystoneParser.java:78)
       at com.kontakt.sdk.android.ble.discovery.eddystone.EddystoneDiscoverer.performDiscovery(EddystoneDiscoverer.java:58)
       at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.performDiscovery(DefaultBluetoothDeviceDiscoverer.java:49)
       at com.kontakt.sdk.android.ble.service.MonitorCallback$2.run(MonitorCallback.java:78)
       at android.os.Handler.handleCallback(Handler.java:914)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7564)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
Obviously the values in the IllegalArgumentException are different in each crash. Unfortunately, we haven't been able to reproduce the error. We've managed to gather the following data from our stack traces:
- Kontakt SDK version: 5.0.12
- Primarily affects Xiaomi devices (95%), with a very small minority (about 5%) of the crashes occurring in TCL devices
- Affects Android 9, 10 and 11

Please let me know if you need additional information about this issue

**Comment by robertbielas** [comment]
@gmetal Good catch. There is an overflow issue if the byte representing the length of the packet has a value bigger than 127 (128, 129... 255) <- those are interpreted as signed (negative) values. A small tweak that will interpret this byte as an unsigned value will do the trick. The fix will be present in the next sdk, stay tuned.

**Comment by robertbielas** [comment]
@gmetal Just pushed sdk 5.0.20, check it out (it will become available in 15 - 20 minutes).

**Comment by gmetal** [comment]
@robertbielas thanks for the swift reply and the new SDK version. We will test the new version and will report back if the issue persists.

**Comment by robertbielas** [comment]
@gmetal Have you experienced any new issues like this?

**Comment by gmetal** [comment]
@robertbielas we've released the updated version a couple of days of ago. So far we haven't seen any crashes. Feel free to close this issue. I will reopen it in case we see further instances with the new version.
