### ISSUE TITLE
VerifyError exception

### ISSUE THREAD

**Issue by pubiqq** [kontaktio/kontakt-android-sdk#214]
After upgrading from 5.0.20 to 5.0.23, the following error occurs:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <some app>, PID: 5133
    java.lang.VerifyError: Rejecting class com.kontakt.sdk.android.ble.cache.IBeaconUniqueIdCache that attempts to sub-type erroneous class com.kontakt.sdk.android.ble.cache.AbstractUniqueIdCache (declaration of 'com.kontakt.sdk.android.ble.cache.IBeaconUniqueIdCache' appears in /data/app/<some path>/base.apk!classes19.dex)
        at com.kontakt.sdk.android.ble.cache.CacheProvider.provideBeaconUniqueIdCache(CacheProvider.java:34)
        at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.<init>(DefaultBluetoothDeviceDiscoverer.java:33)
        at com.kontakt.sdk.android.ble.service.MonitorCallback.<init>(MonitorCallback.java:52)
        at com.kontakt.sdk.android.ble.service.MonitorCallback.<init>(MonitorCallback.java:34)
        at com.kontakt.sdk.android.ble.service.MonitorCallback$1.<init>(MonitorCallback.java:39)
        at com.kontakt.sdk.android.ble.service.MonitorCallback.create(MonitorCallback.java:39)
        at com.kontakt.sdk.android.ble.service.ScanCompatL.createScanConfiguration(ScanCompatL.java:23)
        at com.kontakt.sdk.android.ble.service.ProximityService.onStartScan(ProximityService.java:128)
        at com.kontakt.sdk.android.ble.service.ProximityService$MessagingHandler.handleMessage(ProximityService.java:228)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.VerifyError: Verifier rejected class com.kontakt.sdk.android.ble.cache.AbstractUniqueIdCache: io.reactivex.ObservableSource com.kontakt.sdk.android.ble.cache.AbstractUniqueIdCache.lambda$timer$3$com-kontakt-sdk-android-ble-cache-AbstractUniqueIdCache(java.lang.Long) failed to verify: io.reactivex.ObservableSource com.kontakt.sdk.android.ble.cache.AbstractUniqueIdCache.lambda$timer$3$com-kontakt-sdk-android-ble-cache-AbstractUniqueIdCache(java.lang.Long): [0x4]  can't resolve returned type 'Unresolved Reference: io.reactivex.ObservableSource' or 'Unresolved Reference: io.reactivex.Observable' (declaration of 'com.kontakt.sdk.android.ble.cache.AbstractUniqueIdCache' appears in /data/app/<some path>/base.apk!classes19.dex)
        at com.kontakt.sdk.android.ble.cache.CacheProvider.provideBeaconUniqueIdCache(CacheProvider.java:34) 
        at com.kontakt.sdk.android.ble.service.DefaultBluetoothDeviceDiscoverer.<init>(DefaultBluetoothDeviceDiscoverer.java:33) 
        at com.kontakt.sdk.android.ble.service.MonitorCallback.<init>(MonitorCallback.java:52) 
        at com.kontakt.sdk.android.ble.service.MonitorCallback.<init>(MonitorCallback.java:34) 
        at com.kontakt.sdk.android.ble.service.MonitorCallback$1.<init>(MonitorCallback.java:39) 
        at com.kontakt.sdk.android.ble.service.MonitorCallback.create(MonitorCallback.java:39) 
        at com.kontakt.sdk.android.ble.service.ScanCompatL.createScanConfiguration(ScanCompatL.java:23) 
        at com.kontakt.sdk.android.ble.service.ProximityService.onStartScan(ProximityService.java:128) 
        at com.kontakt.sdk.android.ble.service.ProximityService$MessagingHandler.handleMessage(ProximityService.java:228) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7697) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
E/FirebaseCrashlytics: Error handling uncaught exception
    java.util.concurrent.TimeoutException
        at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:138)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:233)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:155)
        at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:55)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
```

**Comment by robertbielas** [comment]
@pubiqq Welcome again sir!
Yes, this will be fixed soon. Sdk embraces reactiveness. :) But first some problems are mandatory to occur, because life would be too boring otherwise.

As a temporal workaround, please add the following dependencies to your app/build.gradle:
implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
implementation 'io.reactivex.rxjava2:rxjava:2.2.9'
optionally: 
implementation 'com.annimon:stream:1.2.2'
implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1'

I will make sure the next sdk has those in its pom file.

You will probably get another set of problems after this (one additional snippet will need to be included), don't hesitate to come back here to this issue!

**Comment by robertbielas** [comment]
@pubiqq Ok, forget workarounds, just published sdk 5.0.24, should be there within 15 minutes. Check this out and let me know if you have any further issues.

**Comment by pubiqq** [comment]
@robertbielas, sorry for the delay, this works.

P.S. I am somewhat upset that the number of heavy dependencies has increased for no apparent reason, but I hope it will change in the future.

**Comment by robertbielas** [comment]
@pubiqq Thanks for sharing your thoughts on additional dependencies. 

At first glance, yes, sudden additions to the sdk's dependencies may seem redundant.
However, I hope you will see that the usage of each one of them is justified:
- rxJava (this is the heaviest one) makes the implementation more robust and easier to accomplish for the parts of the sdk still written in Java
- kotlin compiler - I hope this is self-explanatory why the move in this direction is important.  
Other libraries (like Streams) are utility tools, that are quite lite in comparison, and very helpful, speeding the process of providing new sdk's features. 

Since sdk's starts embracing Kotlin (sdk is a very old library that was originally implemented in Java, as back in the days Kotlin simply did not exist) you may be right that one day other dependencies will become unnecessary once the full migration from Java to Kotlin is achieved (rx may be replaced by coroutines etc.). In the meantime, as mentioned, they are a great help in the development process since bulk of the code is still pure Java.
