### ISSUE TITLE
Missing OkHttp method when initialising ProximityManager

### ISSUE THREAD

**Issue by markfili** [kontaktio/kontakt-android-sdk#232]
Hi, I'm getting this exception about a missing `setUseSessionTickets` method in the OkHttp package which cannot initialize the ProximityManager:
```
W  Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W  unable to load android socket classes
W  java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W  	at java.lang.Class.getMethod(Class.java:2103)
W  	at java.lang.Class.getDeclaredMethod(Class.java:2081)
W  	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W  	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W  	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W  	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W  	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W  	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W  	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W  	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W  	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W  	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W  	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W  	at com.kontakt.sdk.android.cloud.KontaktCloudImpl.buildHttpClient(KontaktCloudImpl.java:93)
W  	at com.kontakt.sdk.android.cloud.KontaktCloudImpl.<init>(KontaktCloudImpl.java:60)
W  	at com.kontakt.sdk.android.cloud.KontaktCloudFactory.create(KontaktCloudFactory.java:27)
W  	at com.kontakt.sdk.android.cloud.KontaktCloudFactory.create(KontaktCloudFactory.java:17)
W  	at com.kontakt.sdk.android.ble.manager.ProximityManagerImpl.<init>(ProximityManagerImpl.java:45)
W  	at com.kontakt.sdk.android.ble.manager.ProximityManagerFactory.create(ProximityManagerFactory.java:20)
W  	at com.xx.beacons.beacons.ForegroundBluetoothService.setupProximityManager(ForegroundBluetoothService.kt:129)
W  	at com.xx.beacons.xx_beacons.ForegroundBluetoothService.onCreate(ForegroundBluetoothService.kt:50)
W  	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)
W  	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
W  	at android.os.Handler.dispatchMessage(Handler.java:106)
W  	at android.os.Looper.loopOnce(Looper.java:226)
W  	at android.os.Looper.loop(Looper.java:313)
W  	at android.app.ActivityThread.main(ActivityThread.java:8757)
W  	at java.lang.reflect.Method.invoke(Native Method)
W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
W  Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (unsupported,core-platform-api, reflection, allowed)
W  Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (unsupported,core-platform-api, reflection, allowed)
W  Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (unsupported,core-platform-api, reflection, allowed)
```

Setup:
kontaktioSdk 7.1.3
compileSdk 33
device - Android 13

one solution mentions upgrading the OkHttp dependency version to `"com.squareup.okhttp3:okhttp:4.9.1"` but I have to try it yet.

**Comment by markfili** [comment]
it worked by adding the OkHttp dependency
