### ISSUE TITLE
beaconManager.isBluetoothEnabled() crashes application

### ISSUE THREAD

**Issue by andreribeiropinto104** [kontaktio/kontakt-android-sdk#60]
I'm trying to follow up the QuickStarter guide in:
http://developer.kontakt.io/android-sdk/quickstart/#interacting-with-beacons-monitoring-code-sample

So, when I try to use the isBluetoothEnabled() method I got the following error:

```
Process: com.example.beatrizgomes.eddystonebeacon, PID: 11768
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.beatrizgomes.eddystonebeacon/com.example.beatrizgomes.eddystonebeacon.EddistoneBeaconActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
            at com.kontakt.sdk.android.manager.BeaconManager.isBluetoothEnabled(BeaconManager.java:655)
            at com.example.beatrizgomes.eddystonebeacon.EddistoneBeaconActivity.onStart(EddistoneBeaconActivity.java:61)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

My application code looks like this:

```
import android.app.Activity;
import android.bluetooth.BluetoothAdapter;
import android.os.Bundle;
import android.content.Intent;
import android.os.RemoteException;
import android.widget.Toast;


import com.kontakt.sdk.android.configuration.ForceScanConfiguration;
import com.kontakt.sdk.android.configuration.MonitorPeriod;
import com.kontakt.sdk.android.connection.OnServiceBoundListener;
import com.kontakt.sdk.android.device.BeaconDevice;
import com.kontakt.sdk.android.device.Region;
import com.kontakt.sdk.android.manager.BeaconManager;

import java.util.List;
import java.util.Set;


public class EddistoneBeaconActivity extends Activity {

    private static final int REQUEST_CODE_ENABLE_BLUETOOTH = 1;

    private BeaconManager beaconManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_eddistone_beacon);

        beaconManager = BeaconManager.newInstance(this);
        beaconManager.setMonitorPeriod(MonitorPeriod.MINIMAL);
        beaconManager.setForceScanConfiguration(ForceScanConfiguration.DEFAULT);
        beaconManager.registerMonitoringListener(new BeaconManager.MonitoringListener() {
            @Override
            public void onMonitorStart() {} // active scan period starts

            @Override
            public void onMonitorStop() {} // passive scan period starts

            @Override
            public void onBeaconAppeared(final Region region, final BeaconDevice beacon) {} // beacon appeared within desired region for the first time

            @Override
            public void onBeaconsUpdated(final Region venue, final List<BeaconDevice> beacons) {} // beacons that are visible within specified region are provided through this method callback. This method has the same

            @Override
            public void onRegionEntered(final Region venue) {} // Android device enters the Region for the first time

            @Override
            public void onRegionAbandoned(final Region venue) {} // Android device abandons the region
        });
    }


    @Override
    protected void onStart() {
        super.onStart();
            if (!beaconManager.isBluetoothEnabled()) {
                final Intent intent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                startActivityForResult(intent, REQUEST_CODE_ENABLE_BLUETOOTH);
            } else if (beaconManager.isConnected()) {
                try {
                    beaconManager.startRanging();
                } catch (RemoteException e) {
                    e.printStackTrace();
                }

            } else {
                connect();
            }
        }



  @Override
    protected void onStop() {
        super.onStop();
        beaconManager.stopMonitoring();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        beaconManager.disconnect();
        beaconManager = null;
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        if(requestCode == REQUEST_CODE_ENABLE_BLUETOOTH) {
            if(resultCode == Activity.RESULT_OK) {
                connect();
            } else {
                Toast.makeText(this, "Bluetooth not enabled", Toast.LENGTH_LONG).show();
                //getActionBar().setSubtitle("Bluetooth not enabled");
            }
            return;
        }

        super.onActivityResult(requestCode, resultCode, data);
    }

    private void connect() {
        try {
            beaconManager.connect(new OnServiceBoundListener() {
                @Override
                public void onServiceBound() {
                    try {
                        beaconManager.startMonitoring((Set<Region>) Region.EVERYWHERE);
                    } catch (RemoteException e) {
                        e.printStackTrace();
                    }
                }
            });
        } catch (RemoteException e) {
            throw new IllegalStateException(e);
        }
    }
}
```

And my dependencies:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile files('libs/core-sdk-1.0.6.jar')
    compile files('libs/android-sdk_1.0.6.jar')
}
```

Does anyone had the same problem? How can I fix this?

Thanks,

**Comment by jakubkontakt** [comment]
You are using deprecated sdk version.  Please update sdk to latest version 2.0.1 and follow this guide: http://developer.kontakt.io/android-sdk/2.0.0/quickstart/

**Comment by andreribeiropinto104** [comment]
Thank you , I'm using the latest version and now it works. I have other doubts but I will search in the documentation. If I can't find the solution I'll create another issue  :)
