### ISSUE TITLE
onEvent not getting triggered in ProximityManager.ProximityListener

### ISSUE THREAD

**Issue by bshikhar13** [kontaktio/kontakt-android-sdk#63]
I am using the code given on [Link](http://developer.kontakt.io/android-sdk/2.0.0/quickstart/).

`public class RangeActivity extends AppCompatActivity implements                                                                             ProximityManager.ProximityListener{

```
   private static final int REQUEST_CODE_ENABLE_BLUETOOTH = 1;

   private ProximityManager proximityManager;

   private ScanContext scanContext;

   @Override
   protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       setContentView(R.layout.beacon_range_activity);

       proximityManager = new ProximityManager(this);

       IBeaconScanContext iBeaconScanContext = new IBeaconScanContext.Builder()
               .setEventTypes(EnumSet.of(EventType.DEVICE_DISCOVERED,
                       EventType.DEVICE_LOST))
               .setRssiCalculator(RssiCalculators.newLimitedMeanRssiCalculator(5))
               .setIBeaconFilters(Arrays.asList(
                       new IBeaconFilter() {
                           @Override
                           public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
                               return iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR;
                           }
                       },
                       IBeaconFilters.newMajorFilter(34)
               ))
               .build();

       EddystoneScanContext eddystoneScanContext = new EddystoneScanContext.Builder()
               .setEventTypes(EnumSet.of(EventType.SPACE_ENTERED,
                       EventType.SPACE_ABANDONED))
               .setUIDFilters(Arrays.asList(
                       EddystoneFilters.newUIDFilter(KontaktSDK.DEFAULT_KONTAKT_EDDYSTONE_NAMESPACE_ID, "000013")
               ))
               .setURLFilters(Arrays.asList(
                       EddystoneFilters.newURLFilter("http://Kontakt.io")
               ))
               .build();


       scanContext = new ScanContext.Builder()
               .setScanMode(ProximityManager.SCAN_MODE_BALANCED)
               .setIBeaconScanContext(iBeaconScanContext)
               .setEddystoneScanContext(eddystoneScanContext)
               .setActivityCheckConfiguration(ActivityCheckConfiguration.DEFAULT)
               .setForceScanConfiguration(ForceScanConfiguration.DEFAULT)
               .setScanPeriod(new ScanPeriod(TimeUnit.SECONDS.toMillis(5), 0))
               .build();
   }

   @Override
   protected void onResume() {
       super.onResume();

       if (!BluetoothUtils.isBluetoothEnabled()) {
           final Intent intent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
           startActivityForResult(intent, REQUEST_CODE_ENABLE_BLUETOOTH);
       } else {
           initializeScan();
       }
   }

   @Override
   protected void onPause() {
       super.onPause();

       proximityManager.finishScan();
   }

   @Override
   protected void onActivityResult(int requestCode, int resultCode, Intent data) {

       switch(requestCode) {

           case REQUEST_CODE_ENABLE_BLUETOOTH:

               if(resultCode == RESULT_OK) {
                   initializeScan();
               }
               break;

           default:
               super.onActivityResult(requestCode, resultCode, data);
       }
   }

   @Override
   public void onScanStart() {

   }

   @Override
   public void onEvent(BluetoothDeviceEvent event) {
       switch (event.getDeviceProfile()) {

           case IBEACON:
               final IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) event;
               runOnUiThread(new Runnable() {
                   @Override
                   public void run() {
                       IBeaconRegion region = iBeaconDeviceEvent.getRegion();
                       List<IBeaconDevice> deviceList = iBeaconDeviceEvent.getDeviceList();
                   }
               });
               break;

           case EDDYSTONE:
               final EddystoneDeviceEvent eddystoneDeviceEvent = (EddystoneDeviceEvent) event;
               runOnUiThread(new Runnable() {
                   @Override
                   public void run() {
                       IEddystoneNamespace namespace = eddystoneDeviceEvent.getNamespace();
                       List<IEddystoneDevice> deviceList = eddystoneDeviceEvent.getDeviceList();
                   }
               });
               break;

           default:

       }
   }

   @Override
   public void onScanStop() {

   }

   @Override
   protected void onDestroy() {
       super.onDestroy();
       proximityManager.disconnect();
       proximityManager = null;
   }

   private void initializeScan() {
     proximityManager.initializeScan(scanContext, new OnServiceReadyListener() {
           @Override
           public void onServiceReady() {
              proximityManager.attachListener(RangeActivity.this);
           }

           @Override
           public void onConnectionFailure() {
               Utils.showToast(RangeActivity.this, getString(R.string.unexpected_error_connection));
           }
       });
   }
}`
```

**Comment by zibiksior** [comment]
I've been using the same example this week and it's working for me. onEvent is triggered and list of beacon is collected.

I don't know why but I must say that Kontakt's API isn't working so great... I had few problem with it... For example sometimes when I stop scanning and that start it again I'm getting some weird out of bounds exception inside Kontakt libraries. I would recommend you using other libraries. Actually since Android 5 it supports both iBeacon and Eddystone profiles out of the box so i'm pretty sure that you don't have to use this API. I didn't tried that yet but I know that there is also few libraries on the Internet which will let you communicate with beacons easily. Probably some of those libraries could be less buggy than this.

Regards

**Comment by jakubkontakt** [comment]
Hi @zibiksior Do you have by chance a stacktrace of Exception thrown under the hood?

We are trying to make our SDK to not have any bugs, but some of them could be spotted only on few devices and in particular environment. If you have any additional information about your errors please share it with us.

@bshikhar13 

Did you run same example without iBeaconFilters

```
.setIBeaconFilters(Arrays.asList(
    new IBeaconFilter() {
         @Override
         public boolean apply(IBeaconAdvertisingPacket iBeaconAdvertisingPacket) {
              return iBeaconAdvertisingPacket.getProximity() == Proximity.NEAR;
         }
       },
     IBeaconFilters.newMajorFilter(34)
```

and without URLFilters

```
 .setURLFilters(Arrays.asList(
                       EddystoneFilters.newURLFilter("http://Kontakt.io")
               ))
```

**Comment by zibiksior** [comment]
@jakubkontakt I investigated a problem a little bit and I'm not quite sure what is this error connected with... Is it caused by Kontakt API or maybe my ArrayAdapter is not working as it should I don't know because this exception is really random and not thrown in my code but somewhere inside the AndroidRuntime... It happens after I stop/start priximityManager Scanning for a few times. I have two buttons one to start scanning and second to stop scanning and they do this:

<pre><code>
@Override
    public void onClick(View v) {
                switch(v.getId()){
                    case R.id.scanStart:
                        //DO something
                        Log.e("TAG", "SCAN START TAPPED");
                        deviceList.clear();
                        adapter.notifyDataSetChanged();
                       proximityManager.restartScan(scanContext);
                        break;
                    case R.id.scanStop:
                        Log.e("TAG", "SCAN STOP PRESSED");
                        proximityManager.finishScan();
                        myAwesomeTextView.setText("Scanning stopped");
                        break;
                }
    }</code></pre>

I think it's nothing particularly complex.

Exception looks like that:

<pre><code>12-08 18:11:54.547 30645-30645/com.zbigniew.beaconconfigurator E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.zbigniew.beaconconfigurator, PID: 30645
                                                                                 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                                                     at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
                                                                                     at android.widget.ListView.dispatchDraw(ListView.java:3329)
                                                                                     at android.view.View.draw(View.java:16181)
                                                                                     at android.widget.AbsListView.draw(AbsListView.java:4142)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                                     at android.view.View.draw(View.java:15948)
                                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15169)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
</code></pre>

My device: Nexus 5 Android 6.0.
My whole project is shared here: https://github.com/zibiksior/Beacon_Configurator

**Comment by jakubkontakt** [comment]
Hi @zibiksior 
I run your code and I did not received any exceptions. I have not investigated it in details, but it looks like the problem is much more related to your adapter code.

Please check if any of tips provided in [stackoverflow thread](http://stackoverflow.com/questions/8256626/android-index-out-of-bounds-error-with-no-application-code-in-stack-trace) is helpful for you.

@bshikhar13 
Did you run your code without setting filters?
