### ISSUE TITLE
Unable to scan on Android M devices

### ISSUE THREAD

**Issue by emarc-m** [kontaktio/kontakt-android-sdk#70]
It seems that when running on Android Marshmallow devices, location permissions are needed.

I see these logs:
12-24 14:10:42.184 9067-9078/package W/Binder: Caught a RuntimeException from the binder stub implementation.
java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
at android.os.Parcel.readException(Parcel.java:1620)
at android.os.Parcel.readException(Parcel.java:1573)
at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
at android.os.Binder.execTransact(Binder.java:453)

Has the SDK been tested on Android devices running M? Is there a way to not require the location permission? Handling runtime permissions on M is not really ideal for our use case.

Thanks.

**Comment by jakubkontakt** [comment]
Hi @emarc-m 
Yes, with new permissions system scanning beacons require new permission from LOCATION group. Our SDK still works with on Android Marshmallow considering app standby and doze.

If you want to target your application to SDK Api Level 23, then you need to handle new permission system on your own, as there are many different use cases.

But you can as well target below 23 and your app will run.

**Comment by jakubkontakt** [comment]
You can read more about handling runtime permissions with beacons on our site: http://developer.kontakt.io/android-sdk/2.1.0/quickstart/
